/* Generated by Opal 0.10.1 */
(function(Opal) {
  var self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice, $klass = Opal.klass, $gvars = Opal.gvars;

  Opal.add_stubs(['$rand', '$new']);
  (function($base, $super) {
    function $Synth(){};
    var self = $Synth = $klass($base, $super, 'Synth', $Synth);

    var def = self.$$proto, $scope = self.$$scope, TMP_1;

    return (Opal.defn(self, '$clock', TMP_1 = function ːclock() {
      var self = this;

      return self.$rand();
    }, TMP_1.$$arity = 0), nil) && 'clock'
  })($scope.base, null);
  return $gvars.synth = $scope.get('Synth').$new();
})(Opal);

/* Generated by Opal 0.10.1 */
(function(Opal) {
  var self = Opal.top, $scope = Opal, nil = Opal.nil, $breaker = Opal.breaker, $slice = Opal.slice;

  Opal.add_stubs(['$exit']);
  return $scope.get('Kernel').$exit()
})(Opal);
